databases:
  - name: emailsender-db
    databaseName: emailsender
    user: emailsender
    plan: free

services:
  - type: web
    name: bulk-email-sender-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: emailsender-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
